//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Buys = new HashSet<Buy>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string AgentLastName { get; set; }
        public string AgentFirstName { get; set; }
        public long AgentTel { get; set; }
        public string AgentAddress { get; set; }
        public string EMail { get; set; }
        public bool Gender { get; set; }
        public long NationalCode { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
    }
}
