//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int CarID { get; set; }
        public int Count { get; set; }
        public string Date { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Car Car { get; set; }
    }
}
